
permalink:      none
relative_permalinks: true

title:          Neikos' Blog
tagline:        Talking about my work and leisure
description:    Ideas and thoughts I have from time to time
url:            http://neikos.me
paginate:       10
baseurl:        /
author:
    name:       Marcel M&uuml;ller
    email:      marcel-muller@hotmail.com
markdown: redcarpet

gems:
    - jekyll-sitemap


syntax-highlighting:
    enabled: true
    css: syntax.css

highlighter: pygments
