baseURL = "http://neikos.me/"
languageCode = "en-us"
title = "Neikos & Programming"
theme = "minimal"
googleAnalytics = ""
disablePathToLower = true

[params]
    author = "Neiks <Marcel Müller>"
    description = "Thoughts and musings"
    githubUsername = "TheNeikos"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "rust"]
    pages = 5

[outputs]
home = ["HTML","RSS"]

[mediaTypes]
"application/rss" =  { suffixex = ["rss"] }

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:neikos@neikos.email"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/TheNeikos/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://stackoverflow.com/users/783825/neikos"
    name = "stack-overflow"
    weight = 3

[[menu.icon]]
    url = "https://telegram.me/TheNeikos"
    name = "telegram"
    weight = 4

[[menu.icon]]
    url = "https://mastodon.fun/@Neikos"
    name = "random"
    weight = 5
